version: "3"

services:
  database:
    ports:
      - "5555:5432"
  service-library:
    environment:
      - GRAPHIQL=true
    ports:
      - "8080:8080"
  nginx:
    volumes:
      - ./nginx/conf/dev-nginx.conf:/etc/nginx/conf.d/default.conf
  frontend:
    build:
      context: frontend-library
      dockerfile: Dockerfile
    volumes:
      - ./frontend-library/public:/frontend-library/public
      - ./frontend-library/src:/frontend-library/src
      - ./frontend-library/.eslintrc.cjs:/frontend-library/.eslintrc.cjs
      - ./frontend-library/index.html:/frontend-library/index.html
      - ./frontend-library/tsconfig.json:/frontend-library/tsconfig.json
      - ./frontend-library/tsconfig.node.json:/frontend-library/tsconfig.node.json
      - ./frontend-library/vite.config.ts:/frontend-library/vite.config.ts
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]
