version: "3"

services:
  database:
    image: postgres:16-alpine3.17
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db-library
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  service-library:
    build:
      context: service-library
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - GRAPHIQL=false
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"

volumes:
  postgresql-data:
